[build]
  command = "pip install -r requirements.txt && python combined_run.py"
  publish = "ui"  # Directory to publish (for Streamlit static files)

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[functions]
  directory = "api_functions"

[[plugins]]
  package = "netlify-plugin-pyenv"