name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source .venv/bin/activate
        # Add your test command here, e.g., pytest
        echo "No tests specified"

    - name: Start FastAPI server
      run: |
        source .venv/bin/activate
        nohup uvicorn main:app --host 0.0.0.0 --port 8000 &

    - name: Start Streamlit
      run: |
        source .venv/bin/activate
        nohup streamlit run chat_ui.py &

    - name: Post completion status
      run: |
        echo "Application has been set up and is running."

    - name: Upload server logs
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: server-logs
        path: nohup.out
